### ISSUE TITLE
Transaction, PG connection and Async IO

### ISSUE THREAD

**Issue by corporatepiyush** [langpavel/node-pg-async#89]
Does transaction requires a given Postgres connection to be reserved exclusively until commit command or it can be used in another transaction ?

Assuming that someone is using this driver for web application for which all HTTP requests needs transaction, if Postgres connection need to reserved exclusively, then there would be 1 Postgres connection per HTTP request. I wonder How much benefit one might achieve by using this async (non-blocking) driver instead of sync (blocking) driver ?

**Comment by langpavel** [comment]
There is no sync blocking driver for node for good reason. This library needs a little of maintenance, mostly in docs and explain pooling mechanism which is inherited from pg = node-postgres.
This library offers you safe SQL template string, better solution then pg-promise offers

**Comment by vitaly-t** [comment]
> Does transaction requires a given Postgres connection to be reserved exclusively until commit command or it can be used in another transaction ?

Transactions keep what's known as transaction context. The context is reset by opening a new transaction, if it is used within the same connection. So the answer to your question - yes, the transaction connection must be exclusive to the transaction, or else it will get broken. You must never share a connection between a transaction and other parallel queries.

> This library offers you safe SQL template string, better solution then pg-promise offers

This guy is a joke, not only misses the point of the question, but always takes the moment to shit on somebody else's library.

**Comment by corporatepiyush** [comment]
Thanks

**Comment by langpavel** [comment]
@corporatepiyush Sorry if I missed something:
> Does transaction requires a given Postgres connection to be reserved exclusively until commit command or it can be used in another transaction ?

Because of nature of node, you can receive multiple connections during one transaction. If you explicitly `BEGIN` transaction, you don't want different connection to operate on this one connection. If you reuse single connection (which you create on app level), you will effectively make transactions dangerous with very bad side effects.

Let me explain what I think: You need one connection which make all the atomic things in transaction — this is single "customer", single transaction as an atomic (may be complex) operation. During this time other request may happen.
If you reuse this connections and you issue some query which may fail, you will loss everything since first `BEGIN`.

However if you will use only single connection, your queries will be enqueued and they will behave same way as if you reserve one client from the pool for each request. It will be slow but you will not observe this until you write test with parallel requests. Catastrophics scenarios can happen when you `BEGIN` a transaction and some erroneous query will be possible. If previous was not DoS vector, this is :100:.

> Assuming that someone is using this driver for web application for which all HTTP requests needs transaction, if Postgres connection need to reserved exclusively, then there would be 1 Postgres connection per HTTP request. I wonder How much benefit one might achieve by using this async (non-blocking) driver instead of sync (blocking) driver ?

Where is sync — blocking — driver on npm? I choose `async` keyword present in name because promise based APIs can heavily benefit from this language extension.
Benefit? Ok, I will try to explain. Very thin shell around `node-postgres` plus bad man SQL template string which is not actually returning a string but object for `node-postgres`. Let lower levels handle your variables.

Sorry @vitaly-t **you still entirely ignoring correct variable passing mechanism!** Serializing variables by yourself is most vulnerable way of doing this, like magic quotes...
Let this on low level — connection protocol which have better handling of this. If you don't ignore this point every single time I point on this @vitaly-t, I will be using your code, because you had much more impact on OSS community.
See this:
```
> pg.SQL`SELECT a FROM b WHERE b.c=${'c'}`
SqlFragment {
  _parts: [ 'SELECT a FROM b WHERE b.c=', '' ],
  values: [ 'c' ],
  text: 'SELECT a FROM b WHERE b.c=$1' }
```
You see, there is `$1` as variable placeholder.
Your library @vitaly-t create one string with no parameters inlining all arguments directly into query.
This is only blocker for me why I don't want to use your lib @vitaly-t, when you fix this, I will drop support of `pg-async` recommending move to `pg-promise`

If you show me proof that inlining variables and passing variables is effectively same thing (encoding on transport layer, processing inside Postgres LRU cache and parser) I will shift my mind. Until I will still repeat mine mantra :-)

Have a nice day and thanks for your interrest @vitaly-t

**Comment by langpavel** [comment]
Hi @vitaly-t 
I must give you a hold. Really, I apologise. I offer help with `pg-core`. I was out of because It doesn't pain me at the moment, but It can..

You are a very interested person in postgres binding and I wish you success. Brian is actually busy with different things it looks.. you are only people who can fix node+postgres binding right now.
I'm offerring you hand, but please, don't be as stupid and arrogant as I was before.. I see you are doing well for postgres..
Can you give me a right starting point?

**Comment by corporatepiyush** [comment]
@langpavel Thanks for detailed explanation

**Comment by vitaly-t** [comment]
> you will effectively make transactions dangerous with very bad side effects.

To clarify, you will be breaking the transaction integrity.
